Add Junit tests for Activity List Command and Activity View Command
AY2122S2-CS2113T-T10-1/tp pull request #248
Opened 2022-03-16 16:23 UTC by lelerer

2022-03-16 16:30 UTC, warrencxw requested changes
Code is generally okay, just that there are minor standardisation issues to rectify and a simple suggestion from me.

2022-03-16 16:30 UTC, warrencxw commented on src/test/java/seedu/splitlah/command/ActivityListCommandTest.java
> +
Consider removing this newline for standardisation (single line breaks only).

2022-03-16 16:30 UTC, warrencxw commented on src/test/java/seedu/splitlah/command/ActivityListCommandTest.java
> +     * Checks if activities are listed with missing sid.
Consider rephrasing `sid` to `session unique identifier`.
Also consider splitting this test into two separate tests, one without the delimiter `/sid` (`activity /list 1`), one without the argument after `/sid` (`activity /list /sid`).

2022-03-17 01:02 UTC, ivanaitzliddat requested changes
Looks good overall, but can probably refactor a little and change the naming for certain variables.

2022-03-17 01:02 UTC, ivanaitzliddat commented on src/test/java/seedu/splitlah/command/ActivityListCommandTest.java
> +    public void prepare_hasMissingDelimiter_InvalidCommand() {
With regards to the other comment, can possibly split the two cases into two different methods.

2022-03-17 01:59 UTC, froststein approved these changes
Overall looks good to merge, just need to rename a few functions

2022-03-17 01:59 UTC, froststein commented on src/test/java/seedu/splitlah/command/ActivityListCommandTest.java
> +    public void prepare_hasMissingDelimiter_InvalidCommand() {
Consider changing the function name to `prepare_hasMissingArguments_InvalidCommand`

2022-03-17 01:59 UTC, froststein commented on src/test/java/seedu/splitlah/command/ActivityListCommandTest.java
> +    public void prepare_hasMissingArgument_InvalidCommand() {
Consider changing the function name to `prepare_hasMissingDelimiter_InvalidCommand`

2022-03-17 01:59 UTC, froststein commented on src/test/java/seedu/splitlah/command/ActivityViewCommandTest.java
> +    public void prepare_hasMissingDelimiter_InvalidCommand() {
Perhaps making it plural? with `hasMissingDelimiters`

2022-03-17 02:16 UTC, ivanaitzliddat approved these changes
Looks good to merge

2022-03-17 02:17 UTC, merged