Set up GroupCreateCommand class
AY2122S2-CS2113T-T10-1/tp pull request #276
Opened 2022-03-18 12:55 UTC by lelerer

2022-03-18 13:05 UTC, froststein requested changes
Code may contain bugs during usage. Need to perform some standardization. Other than that, they are small changes to be made.

2022-03-18 13:05 UTC, froststein commented on src/main/java/seedu/splitlah/command/GroupCreateCommand.java
> +        int newGroupId = manager.getProfile().getNewGroupId();
Perhaps shift this LOC down to line 130, when all the checks have passed. As getNewGroupId is a function that has an effect in the system's variables. It is best to only call when all checks have been passed.

2022-03-18 13:05 UTC, froststein commented on src/main/java/seedu/splitlah/data/Group.java
> +     * @param groupId An integer that uniquely identifies a group.
May want to align all the @param for standardization.

2022-03-18 15:09 UTC, warrencxw approved these changes
Generally looks good, but many unnecessary new lines have been added which can be removed to standardise with the rest of the code and maintain flow.

2022-03-18 15:09 UTC, warrencxw commented on src/main/java/seedu/splitlah/ui/Message.java
> +
Consider removing these extra new lines here for standardisation.

2022-03-18 15:09 UTC, warrencxw commented on src/main/java/seedu/splitlah/command/GroupCreateCommand.java
> +
Consider removing one new line here for standardisation.

2022-03-18 15:09 UTC, warrencxw commented on src/main/java/seedu/splitlah/command/GroupCreateCommand.java
> +
Consider removing this newline here for standardisation

2022-03-18 15:09 UTC, warrencxw commented on src/main/java/seedu/splitlah/data/Group.java
> +
Consider removing this newline here for standardisation.

2022-03-19 03:06 UTC, ivanaitzliddat approved these changes
Looks good overall, left a small comment to be edited for overall standardization

2022-03-19 03:06 UTC, ivanaitzliddat commented on src/main/java/seedu/splitlah/command/GroupCreateCommand.java
> +     * @return true if it contains duplicates, false otherwise.
Possible to put "false otherwise" on a newline and aligned it with "true if ..."

2022-03-19 09:02 UTC, merged