Add group create and group delete command in UserGuide
AY2122S2-CS2113T-T10-1/tp pull request #325
Opened 2022-03-23 11:09 UTC by lelerer

2022-03-23 14:49 UTC, froststein approved these changes
Overall looks good, just needs to fix some spacing and add a warning section for group delete command.

2022-03-23 14:49 UTC, froststein commented on docs/UserGuide.md
> +
Perhaps add a warning like how `session /delete` does it to warn the user that a delete is irreversible.

2022-03-23 14:49 UTC, froststein commented on docs/UserGuide.md
> +> Creates a new group . <br>
Perhaps remove the extra space between group and .

2022-03-23 15:16 UTC, ivanaitzliddat requested changes
Looks good overall, just a small change, along with others' comments

2022-03-24 02:01 UTC, ivanaitzliddat approved these changes
Looks good to merge

2022-03-24 03:17 UTC, merged