Activity edit command
AY2122S2-CS2113T-T10-1/tp pull request #330
Opened 2022-03-23 20:16 UTC by matheril

This command allows users to edit an activity.
The user only have to include delimiters for the fields they want to edit.
Fields without delimiters will be left unchanged.
The user must include session id and activity id at minimum so the activity to be edited can be found.

2022-03-25 23:50 UTC, froststein requested changes
Generally looks okay to merge, just need to make sure some lines are standardized.

2022-03-25 23:50 UTC, froststein commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +        TextUI ui = manager.getUi();
Perhaps removing this if its not used, because on line 71 you called in directly.
Also for line 63, you may want to consider removing it and updating line 66 to directly call too. 
However, if you wish to persist with the current implementation please standardize line 66 and 71.

2022-03-25 23:50 UTC, froststein commented on src/main/java/seedu/splitlah/parser/commandparser/ActivityEditCommandParser.java
> +
Perhaps add a javadocs explaining what this function does?

2022-03-26 06:28 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +        TextUI ui = manager.getUi();
Resolved

2022-03-26 06:32 UTC, matheril commented on src/main/java/seedu/splitlah/parser/commandparser/ActivityEditCommandParser.java
> +
Resolved

2022-03-26 08:40 UTC, froststein approved these changes
Looks good to merge

2022-03-26 15:41 UTC, warrencxw approved these changes
Looks good to merge.

2022-03-26 15:46 UTC, merged