Add ActivityListCommand in DG
AY2122S2-CS2113T-T10-1/tp pull request #375
Opened 2022-03-29 11:40 UTC by lelerer

2022-03-29 14:56 UTC, warrencxw requested changes
Discrepancies between developer guide and code was found, I left behind some suggestions for you, please take a look.

2022-03-30 02:04 UTC, warrencxw requested changes
Minor suggestion provided to conclude the section smoothly.

2022-03-30 02:04 UTC, warrencxw commented on docs/DeveloperGuide.md
> +or a table summarising the list of activities in the session.
Consider adding a last point to mention that the String returned is then printed out with `TextUI#printlnMessage()`

2022-03-30 02:05 UTC, warrencxw commented on docs/DeveloperGuide.md
> +or a table summarising the list of activities in the session.
Also, consider using either `String object` or `string`, rather than `String` to better clarity.

2022-03-30 02:41 UTC, ivanaitzliddat requested changes
Looks good overall, perhaps just some changes to follow overall standardization

2022-03-30 02:41 UTC, ivanaitzliddat commented on docs/DeveloperGuide.md
> +6. Once the session is retrieved, `ActivityListCommand` class will run call `Session#getActivityListSummaryString` and the
Possible to choose either "run" or "call" rather than both "run call"

2022-03-30 02:41 UTC, ivanaitzliddat commented on docs/DeveloperGuide.md
> +or a table summarising the list of activities in the session.
For this if else portion, can perhaps refer to group /list to follow overall standardization by using additional pointers

2022-03-30 03:03 UTC, warrencxw approved these changes
Looks good to merge.

2022-03-30 03:03 UTC, ivanaitzliddat approved these changes
Looks good to merge

2022-03-30 05:45 UTC, froststein approved these changes
Looks good to merge

2022-03-30 05:46 UTC, merged