Add SessionViewCommand to DeveloperGuide
AY2122S2-CS2113T-T10-1/tp pull request #384
Opened 2022-03-29 18:40 UTC by matheril

Fixes #383

2022-03-30 01:47 UTC, froststein requested changes
Some errors on the type of command being explained.

2022-03-30 01:47 UTC, froststein commented on docs/DeveloperGuide.md
> +The general workflow of the `session /create` command is as follows:
Should change `session /view ` not `session /create`

2022-03-30 01:47 UTC, froststein commented on docs/DeveloperGuide.md
> +**API reference:** [`SessionViewCommand.java`](https://github.com/AY2122S2-CS2113T-T10-1/tp/blob/master/src/main/java/seedu/splitlah/command/SessionCreateCommand.java)
The reference is not the correct reference.

2022-03-30 05:28 UTC, matheril commented on docs/DeveloperGuide.md
> +The general workflow of the `session /create` command is as follows:
Resolved

2022-03-30 05:28 UTC, matheril commented on docs/DeveloperGuide.md
> +**API reference:** [`SessionViewCommand.java`](https://github.com/AY2122S2-CS2113T-T10-1/tp/blob/master/src/main/java/seedu/splitlah/command/SessionCreateCommand.java)
Resolved

2022-03-30 07:38 UTC, warrencxw requested changes
A few consistency issues present. Added a few suggestions that you can follow to fix.

2022-03-30 07:38 UTC, warrencxw commented on docs/DeveloperGuide.md
> +2. `Splitlah` then parses the input by using methods in the `Parser` class to obtain a `SessionViewCommand` object.
Consider changing `Splitlah` to `SplitLah` for consistency.

2022-03-30 07:38 UTC, warrencxw commented on docs/DeveloperGuide.md
> +      `TextUI#printlnMessage`.
Consider changing both instances of `sessionId` to session unique identifier to standardise with Profile component which uses that terminology.

2022-03-30 07:38 UTC, warrencxw commented on docs/DeveloperGuide.md
>  2. `Splitlah` then parses the input by using methods in the `Parser` class to obtain a `SessionListCommand` object.
Likewise here, consider changing `Splitlah` to `SplitLah` for consistency

2022-03-30 07:38 UTC, warrencxw commented on docs/DeveloperGuide.md
> +   Then, the last group is printed with a divider below it, using the method `TextUi#printlnMessageWithDivider()`.
Numbering used here is a little weird, maybe have it be consecutive for better consistency?

I think you have to change this entire part to reflect changes (right now SessionListCommand is updated to use `Profile#getSessionListSummaryString` instead, maybe reference #375 for ActivityListCommand which uses `Session#getActivityListSummaryString`.

2022-03-30 07:42 UTC, matheril commented on docs/DeveloperGuide.md
> +2. `Splitlah` then parses the input by using methods in the `Parser` class to obtain a `SessionViewCommand` object.
Resolved across the DG

2022-03-30 07:42 UTC, matheril commented on docs/DeveloperGuide.md
> +      `TextUI#printlnMessage`.
Resolved

2022-03-30 07:43 UTC, matheril commented on docs/DeveloperGuide.md
>  2. `Splitlah` then parses the input by using methods in the `Parser` class to obtain a `SessionListCommand` object.
Resolved

2022-03-30 07:45 UTC, matheril commented on docs/DeveloperGuide.md
> +   Then, the last group is printed with a divider below it, using the method `TextUi#printlnMessageWithDivider()`.
Oops, I changed this by accident. Reverted

2022-03-30 08:29 UTC, warrencxw approved these changes
Looks good to merge.

2022-03-31 01:37 UTC, froststein approved these changes
Looks good to merge

2022-03-31 05:29 UTC, merged