Update user guide
AY2122S2-CS2113T-T10-1/tp pull request #391
Opened 2022-03-30 16:18 UTC by ivanaitzliddat

Reformat parts of the user guide
Rephrased portions of the user guide
Added new images for user guide

2022-03-30 16:35 UTC, matheril requested changes
Content looks good overall but some language errors should be fixed.

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
> +>- There are 3 editable fields, session name, session date and the people involved in the session.
Consider changing this to "There are three editable fields: " (use a colon instead of a comma) (or use the numeral 3 instead of "three" to be consistent since the rest of the guide uses numerals)

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
> +>    and you wish to edit it to include charlie a valid edit command would be `session /edit /sid /pl Alice Bob Charlie`.
Capitalise the "C" in "Charlie".

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
> +- Edits the session to include charlie. <br><br>
Capitalise the "C" in "Charlie".

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
> +>    * The unique identifier for a session can be retrieved with [`session /list`](#listing-all-sessions-session-list) command.
add a "the" before `session /list`

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
>  >- A confirmation must be given before deletion takes place.
Does SplitLah still have the confirmation prompt for this command?

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
> +Creates a new group so that you do not to always enter the same persons' particulars every session.
The word "have" is missing in "you do not [have] to always..."

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
> +>    * The unique identifier for a gorup can be retrieved with [`group /list`](#listing-all-groups-group-list) command.
typo in the word "group"

2022-03-30 16:35 UTC, matheril commented on docs/UserGuide.md
> +>    * The unique identifier for a group can be retrieved with [`group /list`](#listing-all-groups-group-list) command.
Add a "the" before naming the command.

2022-03-30 17:49 UTC, warrencxw requested changes
Good work proofreading the entire user guide, a few changes are to be made for standardisation and I have added them with suggestions in the comments, please take a look and edit accordingly.

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +>  - More than 1 field can be edited at a single run of the command.
Consider rephrasing "... at a single run ..." to "... in a single run ...".

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +>    and you wish to edit it to include Charlie a valid edit command would be `session /edit /sid /pl Alice Bob Charlie`.
Consider shifting the comma and using session unique identifier instead of ID:
If the session previously created had Alice and Bob with session unique identifier of 1 and you wish to edit it to include Charlie, a valid edit command would be ...

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +- Edits the session name to Class gathering and date to 16-03-2022. <br><br>
"Edits the name of the session to ..." would be better to signify what exactly you are editing.

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +>   - Example: `Alice Tan` is not allowed.
Should this part be included in SessionCreate and SessionEdit as well, especially since names need to be defined there first?

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
>  However, deleted sessions will not be listed.
Consider replacing the future tense used here:
However, deleted sessions are not listed.

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +for both Bob and herself which will be split equally between them later on.<br><br>
Consider replacing the future tense used here:
... which is split equally ...

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +Edits an existing activity so that you can change details of an activity.<br>
Consider adding a 'the' to be clearer in this sentence:
... so that you can change the details ...

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
>    a session with a `SESSION_ID` of 1. It was named *Lunch* with Alice and Bob.<br>
Would using "within" or "in" instead of "part of" be better here?

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
>    a session with a `SESSION_ID` of 1. It was named *Lunch* with Alice and Bob.<br>
Also, consider using present tense here:
The activity is named *Lunch*...

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +However, deleted activities will not be listed.
Consider replacing the future tense used here with present tense:
... deleted activities are not listed.

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +Creates a new group so that you do not to always enter the same persons' particulars every session.
Also consider rephrasing the latter part
... particulars for every session that is participated by the same group of persons.

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +Deletes an existing group so that you can remove groups that you do not need.
Consider rephrasing "do not need" to "no longer need".

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +> - There are 2 editable fields: group name and the people involved in the session.
Consider including the portion regarding how at least one field has to be included in order for the command to run, and how both fields can be edited at the same time, similar to `Session /edit`.

2022-03-30 17:49 UTC, warrencxw commented on docs/UserGuide.md
> +However, deleted groups will not be listed.
Consider using present tense instead of future tense for standardisation:
However, deleted groups are not listed.

2022-03-31 01:42 UTC, froststein approved these changes
Looks good to merge

2022-03-31 01:59 UTC, merged