Add Activity Create and Delete Command in Developer Guide
AY2122S2-CS2113T-T10-1/tp pull request #397
Opened 2022-03-31 04:54 UTC by ivanaitzliddat

Add relevant details in developer guide regarding activity create and delete command

2022-04-01 13:33 UTC, warrencxw requested changes
Consider correcting the few things that I have pointed out in the comments. 

Additionally, for the ActivityCreateCommand sequence diagram, hasNameDuplicates should be placed outside of the Opt frame. Otherwise, you are implying that the method only runs if there are duplicates.

2022-04-01 13:33 UTC, warrencxw commented on docs/DeveloperGuide.md
> +6. The`ActivityDeleteCommand#run` method invokes the `Manager#getProfile` method to retrieve the `Profile` object which stores the list of sessions.
Did you forget something here?

2022-04-01 13:33 UTC, warrencxw commented on docs/DeveloperGuide.md
> +11. The `Session#addActivity` method is called to add the new `Activity` object into the list of activities.
Consider adding a 'then' into the sentence to link the flow from point 10 to point 11.

2022-04-01 13:33 UTC, warrencxw commented on docs/DeveloperGuide.md
> +7. The `ActivityCreateCommand` object updates the cost and cost list by invoking the `ActivityCreateCommand#updateCostAndCostList` method.
I think you forgot something here.

2022-04-03 05:38 UTC, warrencxw approved these changes
Looks good to merge.

2022-04-04 03:19 UTC, froststein approved these changes
Looks good to merge

2022-04-04 03:27 UTC, merged