Update Developer guide
AY2122S2-CS2113T-T10-1/tp pull request #403
Opened 2022-03-31 10:02 UTC by froststein

Integrate feedback from peer review.

Add explanation for SessionEditCommand.

2022-03-31 10:35 UTC, matheril requested changes
Content looks good but changes to phrasing and tense recommended.

2022-03-31 10:35 UTC, matheril commented on docs/DeveloperGuide.md
> +The guide's purpose is to allow readers to understand how the application works internally, so that future engineers could continue working on the project with ease.
Consider changing "could" to "can"

2022-03-31 10:35 UTC, matheril commented on docs/DeveloperGuide.md
> +### How to use this developer guide?
The question mark at the end is unnecessary. Consider removing it.

2022-03-31 10:35 UTC, matheril commented on docs/DeveloperGuide.md
> +
Consider rewording this section to:
SplitLah is divided into eight main components: Manager, Profile, TextUI... (consider making each one a subpoint with deeper indentation)
Each component has its own section in this guide explaining them in detail.
This [diagram] shows the inner workings of how each component interacts with each other.
Splitlah supports a total of 18 commands. However, the `help` and `exit` commands will not be explained in detail. (Consider if saying "we" is necessary here; not sure. It's also fine to remove the sentence about help and exit as this sentence isn't really that important for the reader to know).
Please refer to the [userguide] to find out how to use each command.
Please refer to the [implementation section] to find out how each command is designed and implemented in SplitLah.
Each command's section in this guide contains an API reference link that brings you to the main source code responsible for executing the command.

2022-03-31 10:35 UTC, matheril commented on docs/DeveloperGuide.md
> +
Consider rewording this to (formatting is scuffed here, but should give a rough idea of the indentation)
The `Storage` class is initialized (Might want to standardize UK/US spelling) by the `Manager` class when the application starts.
Upon initialization, the `Storage` class checks if a save file already exists. A save file records user data related to SplitLah even after the application is closed.
 * If a save file is found, the `Storage` class loads data from it into the `Profile` object managed by the `Manager` object (I believe Manager is instantiated so object might be better to say than class. The first point already says "when the application starts" so I don't think it's necessary to emphasize that SplitLah is running).
 * Else, a new save file is created and an empty `Profile` object is created instead. (standardise object/instance)

Only commands that update attributes of the `Profile` object also ensure that the save file is updated to record these changes. They are:
*  create
*  delete
*  edit

Once the command finishes executing, `Manager#saveProfile` is called to update the save file.

*  For example: 
   *      The user enters `group /create /n Highschool Friends /pl Alice Bob`. 
   *      SplitLah recognises this as a `GroupCreateCommand` and creates a new group accordingly.
   *      As this updates the list of groups stored in the `Profile` object, `Manager#saveProfile` is called to update the save file with the newly created group.

All classes associated (not sure if there's a better word to replace "under" that more clearly describes the relationship between these classes?) the `Profile` component implement the `Serializable` class. This allows the `Storage` class to write into the save file without having to pre-process the data.

2022-03-31 10:35 UTC, matheril commented on docs/DeveloperGuide.md
> +7. `SessionEditCommand#run` would check if there is an update for a new list of persons, new session or new session date.
Try to reword this section to present tense

2022-04-01 06:03 UTC, warrencxw requested changes
Added a few suggestions to improve the readability.

2022-04-01 06:03 UTC, warrencxw commented on docs/DeveloperGuide.md
> +   * If there is an update on the session date. It would call `Session#setDateCreated` to set the new session date.
Consider rephrasing this to 
If ...,  `Session#someMethod` is called to set ...

2022-04-01 12:35 UTC, ivanaitzliddat approved these changes
Looks good to merge but left a comment for better phrasing

2022-04-01 12:35 UTC, ivanaitzliddat commented on docs/DeveloperGuide.md
> +* Please refer to [here](#implementation) to find out how each command is designed and implemented in SplitLah.
Perhaps can change "here" to "implementation section" or maybe "please refer here"

2022-04-01 14:48 UTC, matheril approved these changes
Looks good to merge

2022-04-01 14:48 UTC, merged