Bug fix for User Guide
AY2122S2-CS2113T-T10-1/tp pull request #429
Opened 2022-04-02 06:17 UTC by ivanaitzliddat

Fixes #407 , #412 , #413 , #416 , #419 , #420 , #426

2022-04-02 08:44 UTC, matheril approved these changes
Some language changes suggested, but they are minor. Looks good to merge.

2022-04-02 08:44 UTC, matheril commented on docs/UserGuide.md
> +>  creating the session, has to be included.
It might be slightly misleading to say "including the group that was declared..." as the edit command does not take in a group name as an argument. Perhaps rephrase this to "including those part of the group declared when creating the session must be included."

2022-04-02 08:44 UTC, matheril commented on docs/UserGuide.md
> +>  in the calculations.
The phrase "may seem to have occurred" seems vague and passive. Consider replacing it with "may occur". Or rephrase the sentence to:

"All values displayed are rounded off to 2 decimal places." The phrase "rounded off" already implies that inaccuracies may result, but you could modify this to "All values displayed are rounded off to 2 decimal places. This may result in slight inaccuracies." to reiterate this to the user.

2022-04-02 08:44 UTC, matheril commented on docs/UserGuide.md
> +> A group represents one or more individuals. The only benefit of a group is to quickly identify a group of individuals
Consider changing "benefit" to "purpose" to make the language seem more objective.

2022-04-02 08:44 UTC, matheril commented on docs/UserGuide.md
> +> This is mainly to improve user experience when using SplitLah.
This seems vague. "improve user experience" is an umbrella term, so consider narrowing this down to the specific part of the user experience that is improved. Consider:
"Groups help you spend less time adding the same people to multiple sessions". Alternatively, you could just remove this line.

2022-04-02 09:03 UTC, warrencxw requested changes
Only added a single change as Saurav has gave suggestions to most of the places that have be changed.

2022-04-03 06:53 UTC, warrencxw approved these changes
Looks good to merge.

2022-04-03 07:00 UTC, froststein approved these changes
Looks good to merge

2022-04-03 07:01 UTC, merged