Update ActivityEditCommand to have optional arguments
AY2122S2-CS2113T-T10-1/tp pull request #435
Opened 2022-04-02 19:05 UTC by matheril

`ActivityEditCommand` now only requires delimiters for the fields that the user wishes to edit.

The following delimiters are still compulsory to identify the activity to be edited:
`/sid`
`/aid`

Behaviour for different combinations of delimiters:
`/n` : Renames the activity.
`/p` : Changes the payer.
`/i` : Changes the participant list.
`/co` : Changes the overall cost and updates the individual costs of each participant accordingly. Can be used even if the `Activity` was created using the `/cl` delimiter. 
If no participant list is supplied using `/i`, the existing list of participants will be preserved.
If no `/gst` or `/sc` (or both) values are provided, the `/gst` and `/sc` values used to create the `Activity` are preserved and the cost updates taking these into account. If `/gst` or `/sc` (or both) values are provided, they replace the `Activity`'s original `/gst` and `/sc` values (if any) and the cost updates taking these into account. 

`/cl` : Changes the cost list and updates the individual costs of each participant accordingly. Can be used even if the `Activity` was created using the `/co` delimiter. 
If no participant list is supplied using `/i`, the existing list of participants will be preserved.
If the length of the list supplied does not match the list of participants, the command handles this gracefully by printing an error and leaving the original activity untouched.
If no `/gst` or `/sc` (or both) values are provided, the `/gst` and `/sc` values used to create the `Activity` are preserved and the cost updates taking these into account. If `/gst` or `/sc` (or both) values are provided, they replace the `Activity`'s original `/gst` and `/sc` values (if any) and the cost updates taking these into account. 

`Parser` now contains two more methods currently used only by `ActivityEditCommand`: `Parser#parseGstIncludingZero` and `Parser#parseServiceChargeIncludingZero`. Both function almost identically to their counterparts `Parser#parseGst` and `Parser#parseServiceCharge`, but with one change: they return -1 if their respective delimiters are not supplied by the user. This was necessary because the already existing methods returned 0 in this scenario, making it impossible for `ActivityEditCommand` to distinguish between the user not supplying a `/gst` or `/sc` delimiter or the user trying to reset the `/gst` or `/sc` back to 0%.

`Activity` now contains two more private fields: `gst` and `serviceCharge`. They are doubles. These were necessary to help `ActivityEditCommand` get the `gst` and `serviceCharge` values of an existing Activity in order to calculate its cost without any extra charges. This value is then multiplied with any new `gst` or `serviceCharge` values the user supplies to determine the edited cost. 

`Activity` also contains another constructor, which takes in two doubles: `gst` and `serviceCharge`. It sets both fields within the `Activity` object and calls the original constructor to set all remaining fields.

`ActivityCreateCommand` now calls the new constructor to create an `Activity` that stores its `gst` and `serviceCharge` values.

Some changes were made to `ActivityEditCommand` parser to handle optional arguments. `ActivityEditCommand` parser now depends on the `ParserErrors#getMissingDelimiterErrorMessage` method to differentiate exceptions thrown due to missing delimiters (which is intended if the user chooses not to provide them) and exceptions thrown due to invalid formatting (which is not intended).

Fixes #418

2022-04-03 03:29 UTC, froststein requested changes
Needs to change some javadocs and naming convention to follow team's standardization

2022-04-03 03:29 UTC, froststein commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +            session.removeActivity(activityId);
Perhaps you may want to add layer of check where by if the user supplies exactly the same arguments and fields, it would print out "no edits were made"

2022-04-03 03:29 UTC, froststein commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
>      public void run(Manager manager) {
Perhaps move this function all the way to the bottom for standardization

2022-04-03 03:29 UTC, froststein commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +        if (totalCost == -1) {
Perhaps using the constant you have defined earlier to check , rather than using `-1`

2022-04-03 03:29 UTC, froststein commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +     * @param involvedPersonList An ArrayList object containing Person objects.
Perhaps renaming this to `An ArrayList object of Person objects.`

2022-04-03 06:46 UTC, warrencxw requested changes
Several styling suggestions pointed out for improvement of code quality. Consider the suggestions proposed and make changes if deemed necessary.

2022-04-03 06:46 UTC, warrencxw commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +                ^ costList == MISSING_COSTLIST)) {
Is this logic correct? Correct me if I am wrong but:
`involvedList != MISSING_INVOLVEDLIST` : true if involved list exists
`costList == MISSING_COSTLIST` : true if costList does not exist

If condition is true if: 
Missing total cost && Involved list exist && costList does not exist OR
Missing total cost && Involved list does not exist && costList exist..?

And with that you throw exceptions on the following cases in this method:
1. Missing total cost && Involved list exist && costList does not exist
2. Missing total cost && Involved list does not exist && costList exist
3. Involved list exists && costList exists && list length mismatch
4. Involved list exists && list has name duplicates.

After `retrieveDetailsFromOldActivity` is calleld, involvedList should not be missing, and as such you might need to reconsider all these if conditions.

2022-04-03 06:46 UTC, warrencxw commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +            checkForNegativeCosts();
Would there be a need for this -- is there a case where the number could be < 0?

2022-04-03 06:46 UTC, warrencxw commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +            addAllActivityCost(involvedArrayList, payerAsPerson, DUMMY_ACTIVITYID);
Not a problem point if it is accounted for, just check that there is no situation where any of the methods following this one will throw an exception, because SessionSummary will display and use the dummy activity cost if not dealt with, assuming the activityCostId does not get updated later on and the old activity does not get deleted etc.

2022-04-03 06:46 UTC, warrencxw commented on src/main/java/seedu/splitlah/parser/Parser.java
> +     *         -1 if the delimiter is not found.
Please standardise this part to something like the following:
```
Return A double that represents a GST charge in percents if the GST delimiter is found,
       a double value of -1 otherwise.
```
Likewise for the other new method created.

2022-04-03 06:46 UTC, warrencxw commented on src/main/java/seedu/splitlah/parser/commandparser/ActivityEditCommandParser.java
> +            }
You can simplify this to
```
if(!equals) {
    throw new ..
}
```
Likewise for parsePayer, parseInvolved etc.

2022-04-03 06:46 UTC, warrencxw commented on src/test/java/seedu/splitlah/command/ActivityEditCommandTest.java
> +            throws InvalidDataException {
Why is this method throwing InvalidDataException? 
Additionally, no tests are being done with regards to the run command in this JUnit test.
Consider shifting this type of tests to ActivityEditCommandParserTest instead, as parsing tests are more relevant there.

2022-04-03 06:46 UTC, warrencxw commented on src/test/java/seedu/splitlah/command/ActivityEditCommandTest.java
> +        assertEquals(3, editedActivity.getInvolvedPersonList().size());
Command#run is not being called here, and as such, costList will not be edited at all, not because of the command running but rather command not running.
Please check through all your tests to ensure that for JUnit tests that tests the run command, you should actually call the run command and check the side effects of the run command.

2022-04-03 09:39 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
>      public void run(Manager manager) {
Resolved

2022-04-03 09:40 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +        if (totalCost == -1) {
Resolved

2022-04-03 09:41 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +     * @param involvedPersonList An ArrayList object containing Person objects.
Resolved

2022-04-03 09:42 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +    private ArrayList<Person> involvedArrayList = null;
Resolved

2022-04-04 06:43 UTC, ivanaitzliddat requested changes
Looks good overall, left some comments

2022-04-04 09:49 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +                ^ costList == MISSING_COSTLIST)) {
Thank you for checking these in detail. I reworked the logic to fix these issues and will check for any unnecessary asserts/boolean checks.

2022-04-04 09:50 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +            checkForNegativeCosts();
You're right, I believe the parser should handle this already. Resolved by removing this line.

2022-04-04 09:54 UTC, matheril commented on src/main/java/seedu/splitlah/parser/Parser.java
> +     *         -1 if the delimiter is not found.
Fixed

2022-04-04 09:58 UTC, matheril commented on src/main/java/seedu/splitlah/parser/commandparser/ActivityEditCommandParser.java
> +            }
Resolved

2022-04-04 10:02 UTC, matheril commented on src/test/java/seedu/splitlah/command/ActivityEditCommandTest.java
> +        assertEquals(3, editedActivity.getInvolvedPersonList().size());
Resolved

2022-04-04 10:03 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +    double[] costList = MISSING_COSTLIST;
Resolved

2022-04-05 06:46 UTC, matheril commented on src/test/java/seedu/splitlah/command/ActivityEditCommandTest.java
> +            throws InvalidDataException {
Resolved

2022-04-05 07:16 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +            addAllActivityCost(involvedArrayList, payerAsPerson, DUMMY_ACTIVITYID);
Retrieving the involvedPersonList should not cause issues as involvedListPersonArray was created earlier by retrieveDetailsFromOldActivity. Any issues with the personlist would have thrown an exception during that method, before addAllActivityCost.

Removing the old activity should not cause issues as oldActivity was created earlier with session.getActivity(activityId), so an invalid activityId would have thrown an exception at that point before addAllActivityCost.
 
Creating a new activity will only cause issues if any of the parameters are invalid.:

- activityId cannot be invalid here because of the previously mentioned point. An invalid activityName would have been caught by ActivityEditCommandParser.
- totalCost is either calculated based on the costs from the original activity (in which case they must be valid), or supplied by the user. An invalid totalCost supplied by the user would have been caught by ActivityEditCommandParser.
- payerAsPerson was created using session.getPersonByName(name), so any issues would have thrown an exception here before addAllActivityCost.
- involvedPersonList is created using involvedListPersonArray, which should be valid as mentioned in the first point.
- invalid GST/service charge values would have been caught by ActivityEditCommandParser, so any user-supplied values must be valid. If the user does not supply any, they are retrieved from the original activity which can be assumed to be valid.

2022-04-05 07:27 UTC, matheril commented on src/main/java/seedu/splitlah/command/ActivityEditCommand.java
> +            session.removeActivity(activityId);
This might be difficult to implement as the individual activity costs are not stored in the Activity itself, so helper methods will be needed to compare the costlists. I will consider adding this in a future PR if we have time.

2022-04-06 11:44 UTC, warrencxw approved these changes
Looks good to merge.

2022-04-06 14:08 UTC, froststein approved these changes
Looks good to merge

2022-04-07 08:21 UTC, ivanaitzliddat approved these changes
Looks good to merge

2022-04-07 08:24 UTC, merged