Edit ActivityEdit in the UG as it now supports optional arguments
AY2122S2-CS2113T-T10-1/tp pull request #452
Opened 2022-04-05 08:09 UTC by matheril

The UG now details how the activity edit command only requires arguments for the details the user wishes to edit.

Fixes #451

2022-04-07 09:26 UTC, warrencxw requested changes
There is some parts where you can make the UG clearer.

2022-04-07 09:26 UTC, warrencxw commented on docs/UserGuide.md
> +> edit the activity instead. You cannot supply both a total cost and a cost list.
Might want to also add that the second sentence applies only where TOTAL_COST is not provided, otherwise sentence can be misleading. Likewise for cost list below.

Alternatively, maybe indent one further under the first sentence, then put the last sentence on a separate point

2022-04-07 09:45 UTC, matheril commented on docs/UserGuide.md
> +> edit the activity instead. You cannot supply both a total cost and a cost list.
Resolved by removing the sentence.

2022-04-07 09:46 UTC, matheril commented on docs/UserGuide.md
> +> edit the activity instead. You cannot supply both a total cost and a cost list.
Resolved by removing the sentence.

2022-04-09 16:58 UTC, warrencxw approved these changes
Looks good to merge.

2022-04-09 16:59 UTC, merged