Amend according to TA's advise
AY2122S2-CS2113T-T10-1/tp pull request #460
Opened 2022-04-06 13:28 UTC by froststein

2022-04-06 15:39 UTC, matheril requested changes
Minor changes requested

2022-04-06 15:39 UTC, matheril commented on docs/DeveloperGuide.md
> +     * The method would check if the newly provided list of persons contains duplicated names.
Consider changing "would check" to "checks" as future tense doesn't seem necessary here.

2022-04-06 15:39 UTC, matheril commented on docs/DeveloperGuide.md
> +       * If duplicated names are detected, an exception is thrown, an error message would be printed and control is returned to `SplitLah`.
Consider changing "would be printed" to "is printed".

2022-04-06 15:39 UTC, matheril commented on docs/DeveloperGuide.md
> +       * Else, it would call `PersonList#isSuperSet` to check if the newly supplied list of persons contains all existing persons in the session.
Consider changing "would call" to "calls".

2022-04-06 15:39 UTC, matheril commented on docs/DeveloperGuide.md
> +       * Else, a new list of persons ready to be stored in the session is returned
This line is missing a full stop at the end.

2022-04-06 15:39 UTC, matheril commented on docs/DeveloperGuide.md
> +The `GroupCreateCommand` parses only the name and list of persons to store as compared to `SessionCreateCommand` and it creates a new `Group`
Minor, but consider splitting this line into two bullet points: one for each command. Maybe something like

The interactions of GroupCreateCommand with `Profile` and `Storage` classes are identical but the key differences lie in the arguments being parsed:

- `GroupCreateCommand` parses only the name and list of persons. It then creates a new `Group` object and adds it to the list of groups managed by the `Profile` class.
- `SessionCreateCommand` parses the x, y, z.... It then creates a new .... and stores it in .....

But you can choose not to do this if it seems overly repetitive. In that case, do try to split the sentence up into two like the first bullet point to make it easier to follow.

2022-04-07 03:53 UTC, warrencxw approved these changes
Looks good to merge.

2022-04-07 08:29 UTC, matheril requested changes
Looks good to merge after making a minor capitalisation change

2022-04-07 08:29 UTC, matheril commented on docs/DeveloperGuide.md
> +command. When it receives a command from the user, it invokes the `parser` and retrieve the command for SplitLah
Consider capitalising the P in `parser`.

2022-04-07 08:40 UTC, matheril requested changes
Looks good to merge

2022-04-07 08:40 UTC, matheril approved these changes
Looks good to merge

2022-04-07 08:41 UTC, merged