Update developer guide
AY2122S2-CS2113T-T10-1/tp pull request #477
Opened 2022-04-09 10:35 UTC by ivanaitzliddat

Update till session related commands

2022-04-09 14:41 UTC, froststein approved these changes
Looks good to merge

2022-04-09 15:27 UTC, warrencxw requested changes
Added many suggestions, please refer to the comments and edit as necessary.

2022-04-09 15:27 UTC, warrencxw commented on docs/DeveloperGuide.md
> +  returns a `Command` object representing an instruction that the user has for SplitLah.<br>
"to parse ... and to return", nothing wrong here, should not be edited.

2022-04-09 15:27 UTC, warrencxw commented on docs/DeveloperGuide.md
> +5. The created `XYZCommand` object is returned to the `SplitLah` object to run.
Consider keeping the word then to maintain the flow of the discussion.

2022-04-09 15:27 UTC, warrencxw commented on docs/DeveloperGuide.md
> +  * [Parser of commands](#parsing-of-commands)
Maybe "Parsing of commands" instead would be more representative.

2022-04-09 15:27 UTC, warrencxw commented on docs/DeveloperGuide.md
> +When it receives an input from the user, it invokes the `Parser` and retrieve a command corresponding to the input for SplitLah
Consider correcting the grammatical error here: It should be "invokes ... and retrieves ...".

2022-04-09 15:27 UTC, warrencxw commented on docs/DeveloperGuide.md
> +      message is returned by the method, which returns an `InvalidCommand` object to `SplitLah`.
This change is a little weird, consider rephrasing for better flow. What is referred to by "which"?

2022-04-09 15:27 UTC, warrencxw commented on docs/DeveloperGuide.md
> +8. Following that, The `XYZCommand` object is returned from `XYZCommandParser` to `Parser` class,
Consider correcting the case used to lower case for "The".

2022-04-09 15:27 UTC, warrencxw commented on docs/DeveloperGuide.md
> +   * Else, a `String` object containing information regarding all transactions that have to be made is returned.
Consider removing "instead" if you were to shift the previous clause down.

2022-04-10 04:12 UTC, froststein requested changes
Requested change

2022-04-10 07:30 UTC, warrencxw approved these changes
Looks good to merge.

2022-04-10 09:41 UTC, froststein approved these changes
Looks good to merge

2022-04-10 09:41 UTC, merged