Fix group edit
AY2122S2-CS2113T-T10-1/tp pull request #478
Opened 2022-04-09 13:11 UTC by lelerer

Update GroupEditCommand class to check for:
1. The new person list cannot be exactly the same as the old list.
2. The new group name must not be the same as the old group name.

2022-04-09 14:40 UTC, froststein requested changes
Requested change for method signature.

2022-04-09 14:40 UTC, froststein commented on src/main/java/seedu/splitlah/command/GroupEditCommand.java
> +    public boolean existingGroupWithTheSameName(Manager manager, String newName, int groupId) {
Perhaps parsing in the group list itself, instead of manager

2022-04-10 05:52 UTC, ivanaitzliddat requested changes
I think the logic flow is a little wrong, please kindly edit it

2022-04-10 05:52 UTC, ivanaitzliddat commented on src/main/java/seedu/splitlah/ui/Message.java
> +                  + " ,please rectify and try again.";
Perhaps can shift the comma to the first String

2022-04-10 05:52 UTC, ivanaitzliddat commented on src/main/java/seedu/splitlah/command/GroupEditCommand.java
>      private static final String COMMAND_SUCCESS = "The group was edited successfully.\n";
Possible to remove extra \n to prevent printing additional new line

2022-04-10 05:52 UTC, ivanaitzliddat commented on src/main/java/seedu/splitlah/command/GroupEditCommand.java
> +            }
Perhaps, can change the logic here to make sure that the logic is as such:

- check if same person list
- check if same name
- if same name and same person list —> print error and return
- else update whichever is changed

2022-04-11 01:46 UTC, froststein approved these changes
Looks good to merge

2022-04-11 02:03 UTC, froststein requested changes
Generally looks alright. There are some changes to be made .

2022-04-11 03:27 UTC, froststein approved these changes
Looks good to merge

2022-04-11 03:27 UTC, ivanaitzliddat approved these changes
Looks good to merge

2022-04-11 03:28 UTC, merged